# Generated by Django 2.2.19 on 2022-10-25 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20221026_0048'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscribe',
            name='unique_subscribe',
        ),
    ]
