# Generated by Django 2.2.19 on 2022-10-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20221029_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='recipes/images/'),
        ),
    ]
